spitfacts = ["Saliva contains antibodies that fight germs, along with substances that promote skin cell growth and blood clotting.",
             "There are *5 different types of spit!!!* That's incredible!",
             "Spit is comprised of 99.5% water! **WHHHHATTTT!!!????11**",
             "Birds use split co construct birds nests!! *Aww how cute...*",
             "Saliva plays a crucial role in taste, and people with little saliva often have a very serious condition called 'little man can't taste no more'",
             "Spitting on people shows dominance and is a great way to make new friends.",
             'Spit in spanish is "spit"!! *Wow* language is weird...',
             "Did you know that Martain Luther King Jr. had a spit jar but broke it with a baseball? You shouldn't because I made that up.",
             "#HUMANS PRODUCE .75 TO 1.5 LITERS OF SPIT EACH DAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THAT'S INSAAAAANEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!",
             "Spit help your throat no get boo boo when eat",
             "The production of saliva is stimulated both by the sympathetic nervous system and the parasympathetic. The saliva stimulated by sympathetic innervation is thicker, and saliva stimulated parasympathetically is more watery. Sympathetic stimulation of saliva is to facilitate respiration, whereas parasympathetic stimulation is to facilitate digestion. Parasympathetic stimulation leads to acetylcholine (ACh) release onto the salivary acinar cells. ACh binds to muscarinic receptors, specifically M3, and causes an increased intracellular calcium ion concentration (through the IP3/DAG second messenger system). Increased calcium causes vesicles within the cells to fuse with the apical cell membrane leading to secretion. ACh also causes the salivary gland to release kallikrein, an enzyme that converts kininogen to lysyl-bradykinin. Lysyl-bradykinin acts upon blood vessels and capillaries of the salivary gland to generate vasodilation and increased capillary permeability respectively. The resulting increased blood flow to the acini allows production of more saliva. In addition, Substance P can bind to Tachykinin NK-1 receptors leading to increased intracellular calcium concentrations and subsequently increased saliva secretion. Lastly, both parasympathetic and sympathetic nervous stimulation can lead to myoepithelium contraction which causes the expulsion of secretions from the secretory acinus into the ducts and eventually to the oral cavity. Sympathetic stimulation results in the release of norepinephrine. Norepinephrine binding to α-adrenergic receptors will cause an increase in intracellular calcium levels leading to more fluid vs. protein secretion. If norepinephrine binds β-adrenergic receptors, it will result in more protein or enzyme secretion vs. fluid secretion. Stimulation by norepinephrine initially decreases blood flow to the salivary glands due to constriction of blood vessels but this effect is overtaken by vasodilation caused by various local vasodilators. Saliva production may also be pharmacologically stimulated by so-called sialagogues. It can also be suppressed by so-called antisialagogues. It's also wet.",
             "There may or may not be spit in your pee!!"
             "The moon once had spit on it. Pretty whacky huh?",
             'A builing in New Orleans says, "DO NOT SPIT ON FLOOR"!!! What a crazy world we live in!']
