thanks = ['Me too thanks',
          'M-me too thanks?',
          'Haha yes me too thanks',
          'Me too - T. Hanks',
          'Im included too, thanks - me',
          'sknaht oot eM',
          '01001101 01100101 00100000 01110100 01101111 01101111 00100000 01110100 01101000 01100001 01101110 01101011 01110011',
          'Thanks from me too',
          'Thanks from me to you too. ^P.S. ^Thanks',
          'Thanks, me too',
          'Too, me thanks',
          'M3 t00 th4nk2',
          'You have my thanks, for I find the need to agree and/or be apart of the moment you are speaking about. Thanks',
          'M ^e  t ^o o  ^t h ^a n ^k s',
          '#Me too thanks',
          '^Me ^too ^thanks',
          '^^Me ^^too ^^thanks',
          '^^^Me ^^^too ^^^thanks',
          '~~No thanks~~ Me too thanks',
          '*Me too thanks*',
          '**Me too thanks**',
          '***Me too thanks***',
          'Mean tooth banks',
          'Bean booth banks',
          'Flea boo flanks',
          'Me ^me ^too ^thanks too thanks',
          'Me ^me ^^me ^^too ^^thanks ^too ^thanks too thanks',
          'Me ^me ^^me ^^^me ^^^too ^^^thanks ^^too ^^thanks ^too ^thanks too thanks',
          '**Oh thank god!** I thought I was the only one. Me too thanks my friend… *Me too thanks...*',
          'Y-yeah me-me too thanks…',
          'Haha this Reddit thing sure is fun! Me too thanks good friend!',
          '#SUBLIMINAL^^^^^me ^^^^^too ^^^^^thanks MESSAGE',
          'By replying “Me too thanks” you will enter yourself into the Reddit spit facts newsletter. *For all your spit fact needs™!*',
          'Elon Musk has said in a 2017 interview that “Me too thanks” shows signs of untrust towards our new battery powered future. I’ll be the one laughing when I get my solar powered roof and lithium ion battery walls! #MARS2020BABY',
          'Me *toot* thanks. ^tee ^hee',
          '~~My phone is dying my wife left me and I’m stuck on the freeway please for the love of god give me karma~~ Me too thanks.',
          'Me: You too, have my thanks',
          '#M ^E  T ^O O  ^T H ^A N ^K S',
          'Meme tooth hanks',
          '~~I just want karma~~ Me too thanks',
          '~~End me~~ Me too thanks',
          '*beep boop* **comment.reply(“Me too thanks”)** *beep boop*',
          'CONGRATULATIONS!! You are the ^1 0 ^0 0 ^th commenter! Reply *“Me too thanks”* to win a***FREE IPAD!!!!!2211***',
          'yo también gracias',
          '4d 65 20 74 6f 6f 20 74 68 61 6e 6b 73',
          'Me too thanks',
          'ʍɛ ȶօօ ȶɦǟռӄֆ',
          'mє tσσ thαnks',
          '爪乇 ㄒㄖㄖ ㄒ卄卂几Ҝ丂',
          '#M^m^m^m^m^m^m^m^m^m^m e^e^e^e^e^e^e^e^e^e^e^e^e^e &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; t^t^t^t^t^t^t^t^t^t^t^t^t^t^t^t o^o^o^o^o^o^o^o^o^o^o^o^o^o o^o^o^o^o^o^o^o^o^o^o^o^o &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; t^t^t^t^t^t^t^t^t^t^t^t^t^t^t^t h^h^h^h^h^h^h^h^h^h^h^h^h^h a^a^a^a^a^a^a^a^a^a^a^a^a^a n^n^n^n^n^n^n^n^n^n^n^n^n^n k^k^k^k^k^k^k^k^k^k^k^k^k^k s^s^s^s^s^s^s^s^s^s^s^s^s^s^s',
          "Somebody once told *me too thanks* the world is gonna roll *me too thanks*. I ain't the sharpest tool in the shed. *She too thanks* was looking kind of dumb with *her too thanks* finger and her thumb. In the shape of an 'L' on *her too thanks* forehead",
          "A B C D E F G, H I J K, L-M-N-O-P. Q R S, T U V, W X, Y and Z. Now you know your ABC's; next time wont you sing with *me too thanks*",
          "*WOW*. Me and you are on *the exact. same. page.* I **cannot express how amazing this is!!1** *Me too thanks!!* ^^^you're ^^^great",
          "Y'know, I wansn't really jivin' with whatever OP was spittin', but you really changed my mind. So I'm gonna have t' give y'all a good ol' me too thanks",
          '#Me too thanks',
          '#ME TOO THANKS',
          '#M^e ^t^o^o ^^t^h^a^n^k^s',
          "What the fuck did you just fucking say about *me too thanks*, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in nu-*me too thanks*-rous secret raids on Al-Quaeda, and I have over 300 confir*me too thanks*d kills. I am trained in gorilla warfare and I’m the top sniper in the entire US ar-*me too thanks*-d forces. You are nothing to *me too thanks* but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to *me too thanks* over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anyti-*me too thanks*, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unar-*me too thanks*-d combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” com-*me too thanks*-nt was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo. ^^^Me ^^^too ^^^thanks",
          'ｍｅ ｔｏｏ ｔｈａｎｋｓ',
          'ⓂⒺ ⓉⓄⓄ ⓉⒽⒶⓃⓀⓈ',
          'ﾶ乇 ｲのの ｲんﾑ刀ズ丂',
          'm3 700 7h4nk5',
          '( ͝° ͜ʖ͡°)つMe too thanks',
          '┴┬┴┤Me too thanks├┬┴┬',
          '( ͡° ͜ʖ ( ͡° ͜ʖ ( ͡° ͜ʖ (Me too thanks) ͜ʖ ͡°)ʖ ͡°)ʖ ͡°)',
          '(╯°□°）╯︵ sʞuɐɥʇ ooʇ ǝɯ',
          'ɯǝ ʇoo ʇɥɐuʞs ︵ヽ(`Д´)ﾉ︵﻿ sʞuɐɥʇ ooʇ ǝɯ',
          '( ͡° ͜ʖ ͡°)━☆ﾟ.*･｡ﾟMe too thanks*',
          '( ͡° ͜ʖ ͡°)>⌐■-■ &nbsp; (⌐▀͡ ̯ʖ▀)  &nbsp; *Me too thanks*',
          '#M^^e^t^o^o^t^h^a^n^k^s e^t^o^o^t^h^a^n^k^s &nbsp; t^o^o^t^h^a^n^k^s o^o^t^h^a^n^k^s o^t^h^a^n^k^s &nbsp; t^h^a^n^k^s h^a^n^k^s a^n^k^s n^k^s  k^s s',
          'HAHAHA YES HUMAN IM INCLUDED ALSO. *print(humanNoises)*',
          'print("Congratulations commenter {0}! You have been randomly entered into the "Me too thanks" program!", commentNumber)',
          'Wii U thanks',
          'Green blue thanks',
          "I'm included also"]
